services:
  # Frontend - Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=https://grants.etownz.com/api
      - NEXT_PUBLIC_SANITY_PROJECT_ID=hpmuagfn
      - NEXT_PUBLIC_SANITY_DATASET=production
    ports:
      - "3001:3001"
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=8001
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
      - ELASTIC_EMAIL_SMTP_HOST=${ELASTIC_EMAIL_SMTP_HOST}
      - ELASTIC_EMAIL_SMTP_PORT=${ELASTIC_EMAIL_SMTP_PORT}
      - ELASTIC_EMAIL_SMTP_USER=${ELASTIC_EMAIL_SMTP_USER}
      - ELASTIC_EMAIL_SMTP_PASS=${ELASTIC_EMAIL_SMTP_PASS}
      - ELASTIC_EMAIL_FROM_EMAIL=${ELASTIC_EMAIL_FROM_EMAIL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_EMAIL_LIST=${ADMIN_EMAIL_LIST}
      - ENABLE_AUTOMATION=${ENABLE_AUTOMATION}
      - FRONTEND_URL=${FRONTEND_URL}
      - MCP_FETCH_SERVER_URL=http://localhost:9001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # AI Crawler Service
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=etownz_grants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
