services:
  # Frontend - Next.js
  frontend:
    image: registry.digitalocean.com/etownz-grants-container/frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://grants.etownz.com/api
      - NEXT_PUBLIC_SANITY_PROJECT_ID=hpmuagfn
      - NEXT_PUBLIC_SANITY_DATASET=production
    ports:
      - "3001:3000"
    restart: unless-stopped

  # Backend API
  backend:
    image: registry.digitalocean.com/etownz/backend:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
      - ELASTIC_EMAIL_SMTP_HOST=${ELASTIC_EMAIL_SMTP_HOST}
      - ELASTIC_EMAIL_SMTP_PORT=${ELASTIC_EMAIL_SMTP_PORT}
      - ELASTIC_EMAIL_SMTP_USER=${ELASTIC_EMAIL_SMTP_USER}
      - ELASTIC_EMAIL_SMTP_PASS=${ELASTIC_EMAIL_SMTP_PASS}
      - ELASTIC_EMAIL_FROM_EMAIL=${ELASTIC_EMAIL_FROM_EMAIL}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # MCP Documentation Server
  mcp-docs:
    image: registry.digitalocean.com/etownz/mcp-docs:latest
    environment:
      - NODE_ENV=production
      - PROJECT_ROOT=/project
    volumes:
      - ./:/project
    ports:
      - "9000:9000"
    restart: unless-stopped

  # MCP Fetch Server
  mcp-fetch:
    image: registry.digitalocean.com/etownz/mcp-fetch:latest
    environment:
      - NODE_ENV=production
    ports:
      - "9001:9001"
    restart: unless-stopped

  # MCP Filesystem Server
  mcp-filesystem:
    image: registry.digitalocean.com/etownz/mcp-filesystem:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./documents:/app/documents
      - ./templates:/app/templates
    ports:
      - "9002:9002"
    restart: unless-stopped

  # MCP Document Processor
  mcp-document-processor:
    image: registry.digitalocean.com/etownz/mcp-document-processor:latest
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./documents:/app/documents
      - ./templates:/app/templates
    ports:
      - "9003:9003"
    depends_on:
      - mcp-filesystem
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=etownz_grants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge