name: Build Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci --legacy-peer-deps
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Check build output
      working-directory: ./frontend
      run: |
        echo "Checking if build was successful..."
        if [ -d ".next" ]; then
          echo "✅ Build directory exists"
          echo "Build info:"
          ls -la .next/
        else
          echo "❌ Build directory missing"
          exit 1
        fi
        
    - name: Check for knowledge-base route
      working-directory: ./frontend
      run: |
        echo "Checking for knowledge-base in build manifest..."
        if grep -q "knowledge-base" .next/app-build-manifest.json 2>/dev/null || \
           grep -q "knowledge-base" .next/build-manifest.json 2>/dev/null || \
           find .next -name "*knowledge-base*" | grep -q .; then
          echo "✅ Knowledge-base route found in build"
        else
          echo "⚠️ Knowledge-base route might not be in build"
        fi

  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Build backend
      working-directory: ./backend
      run: npm run build
      
    - name: Check build output
      working-directory: ./backend
      run: |
        echo "Checking if build was successful..."
        if [ -d "dist" ]; then
          echo "✅ Build directory exists"
          echo "Build contains:"
          find dist -type f -name "*.js" | head -10
        else
          echo "❌ Build directory missing"
          exit 1
        fi

  docker-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Test Frontend Docker Build
      run: |
        docker build -f frontend/Dockerfile -t test-frontend:latest ./frontend
        
    - name: Test Backend Docker Build
      run: |
        docker build -f backend/Dockerfile.dev -t test-backend:latest ./backend
        
    - name: Verify Frontend Image
      run: |
        echo "Frontend image details:"
        docker images test-frontend:latest
        docker run --rm test-frontend:latest ls -la || echo "Note: Container might exit immediately in production mode"